import fs from 'fs';

const file = 'src/lib/i18n/dictionaries.ts';
let content = fs.readFileSync(file, 'utf8');

// First add English serviceHooks (after services.detail.startConversation)
const enConvIdx = content.indexOf('"services.detail.startConversation": "Start a conversation"');
const enLineEnd = content.indexOf('\n', enConvIdx);
const enHooks = [
  '  "serviceHooks.pacs-membership.question": "Want access to credit and services?",',
  '  "serviceHooks.pacs-membership.b0": "Affordable credit",',
  '  "serviceHooks.pacs-membership.b1": "Storage & inputs",',
  '  "serviceHooks.pacs-membership.b2": "Grievance support",',
  '  "serviceHooks.short-term-crop-credit.question": "Need credit for your crop?",',
  '  "serviceHooks.short-term-crop-credit.b0": "Covers seasonal farming needs",',
  '  "serviceHooks.short-term-crop-credit.b1": "Subsidised interest",',
  '  "serviceHooks.godown-storage.question": "Looking for safe storage?",',
  '  "serviceHooks.godown-storage.b0": "Avoid distress sales",',
  '  "serviceHooks.godown-storage.b1": "Pledge loans against stock",',
  '  "serviceHooks.agro-input-supply.question": "Need quality seeds and fertiliser?",',
  '  "serviceHooks.agro-input-supply.b0": "Certified inputs",',
  '  "serviceHooks.agro-input-supply.b1": "Fair cooperative prices",',
  '  "serviceHooks.pmfby-enrolment.question": "Want crop insurance coverage?",',
  '  "serviceHooks.pmfby-enrolment.b0": "Natural calamity protection",',
  '  "serviceHooks.pmfby-enrolment.b1": "Low premium rates",',
  '  "serviceHooks.cooperative-subsidy.question": "Need funding for cooperative infra?",',
  '  "serviceHooks.cooperative-subsidy.b0": "Capital subsidies",',
  '  "serviceHooks.cooperative-subsidy.b1": "Interest subvention",',
  '  "serviceHooks.pm-fb-enrollment.question": "Need help with crop insurance?",',
  '  "serviceHooks.pm-fb-enrollment.b0": "Free enrolment assistance",',
  '  "serviceHooks.pm-fb-enrollment.b1": "Claim filing support",',
  '  "serviceHooks.cooperative-training.question": "Want to build cooperative skills?",',
  '  "serviceHooks.cooperative-training.b0": "Management courses",',
  '  "serviceHooks.cooperative-training.b1": "Legal compliance training",',
  '  "serviceHooks.digital-banking.question": "Need digital banking access?",',
  '  "serviceHooks.digital-banking.b0": "UPI & net banking",',
  '  "serviceHooks.digital-banking.b1": "Mobile banking apps",',
].join('\n');
content = content.slice(0, enLineEnd + 1) + '\n' + enHooks + '\n' + content.slice(enLineEnd + 1);

// Language-specific hooks
const langHooks = {
  hi: {
    'serviceHooks.pacs-membership.question': 'कर्ज और सेवाओं तक पहुँच चाहते हैं?',
    'serviceHooks.pacs-membership.b0': 'सस्ता कर्ज',
    'serviceHooks.pacs-membership.b1': 'भंडारण और इनपुट',
    'serviceHooks.pacs-membership.b2': 'शिकायत सहायता',
    'serviceHooks.short-term-crop-credit.question': 'अपनी फसल के लिए कर्ज चाहिए?',
    'serviceHooks.short-term-crop-credit.b0': 'मौसमी खेती की जरूरतें पूरी करता है',
    'serviceHooks.short-term-crop-credit.b1': 'सब्सिडी वाली ब्याज दर',
    'serviceHooks.godown-storage.question': 'सुरक्षित भंडारण ढूँढ रहे हैं?',
    'serviceHooks.godown-storage.b0': 'जबरदस्ती बिक्री से बचें',
    'serviceHooks.godown-storage.b1': 'स्टॉक के बदले गिरवी ऋण',
    'serviceHooks.agro-input-supply.question': 'अच्छे बीज और खाद चाहिए?',
    'serviceHooks.agro-input-supply.b0': 'प्रमाणित इनपुट',
    'serviceHooks.agro-input-supply.b1': 'उचित सहकारी मूल्य',
    'serviceHooks.pmfby-enrolment.question': 'फसल बीमा कवरेज चाहिए?',
    'serviceHooks.pmfby-enrolment.b0': 'प्राकृतिक आपदा सुरक्षा',
    'serviceHooks.pmfby-enrolment.b1': 'कम प्रीमियम दर',
    'serviceHooks.cooperative-subsidy.question': 'सहकारी इन्फ्रा के लिए फंडिंग चाहिए?',
    'serviceHooks.cooperative-subsidy.b0': 'पूंजी सब्सिडी',
    'serviceHooks.cooperative-subsidy.b1': 'ब्याज अनुदान',
    'serviceHooks.pm-fb-enrollment.question': 'फसल बीमा में मदद चाहिए?',
    'serviceHooks.pm-fb-enrollment.b0': 'मुफ्त नामांकन सहायता',
    'serviceHooks.pm-fb-enrollment.b1': 'दावा दायर करने में सहायता',
    'serviceHooks.cooperative-training.question': 'सहकारी कौशल बनाना चाहते हैं?',
    'serviceHooks.cooperative-training.b0': 'प्रबंधन पाठ्यक्रम',
    'serviceHooks.cooperative-training.b1': 'कानूनी अनुपालन प्रशिक्षण',
    'serviceHooks.digital-banking.question': 'डिजिटल बैंकिंग एक्सेस चाहिए?',
    'serviceHooks.digital-banking.b0': 'UPI और नेट बैंकिंग',
    'serviceHooks.digital-banking.b1': 'मोबाइल बैंकिंग ऐप्स',
  },
  mr: {
    'serviceHooks.pacs-membership.question': 'कर्ज आणि सेवांचा लाभ घेऊ इच्छिता?',
    'serviceHooks.pacs-membership.b0': 'परवडणारे कर्ज',
    'serviceHooks.pacs-membership.b1': 'साठवणूक आणि साहित्य',
    'serviceHooks.pacs-membership.b2': 'तक्रारी सहाय्य',
    'serviceHooks.short-term-crop-credit.question': 'तुमच्या पिकासाठी कर्ज हवे आहे?',
    'serviceHooks.short-term-crop-credit.b0': 'हंगामी शेतीच्या गरजा पूर्ण करते',
    'serviceHooks.short-term-crop-credit.b1': 'अनुदानित व्याज दर',
    'serviceHooks.godown-storage.question': 'सुरक्षित साठवणूक शोधत आहात?',
    'serviceHooks.godown-storage.b0': 'जबरजस्त विक्री टाळा',
    'serviceHooks.godown-storage.b1': 'स्टॉक विरुद्ध गहाण कर्ज',
    'serviceHooks.agro-input-supply.question': 'चांगले बियाणे आणि खत हवे आहे?',
    'serviceHooks.agro-input-supply.b0': 'प्रमाणित साहित्य',
    'serviceHooks.agro-input-supply.b1': 'योग्य सहकारी किंमत',
    'serviceHooks.pmfby-enrolment.question': 'पीक विमा कव्हरेज हवा आहे?',
    'serviceHooks.pmfby-enrolment.b0': 'नैसर्गिक आपत्ती संरक्षण',
    'serviceHooks.pmfby-enrolment.b1': 'कमी प्रीमियम दर',
    'serviceHooks.cooperative-subsidy.question': 'सहकारी पायाभूत सुविधांसाठी निधी हवा आहे?',
    'serviceHooks.cooperative-subsidy.b0': 'भांडवल अनुदान',
    'serviceHooks.cooperative-subsidy.b1': 'व्याज अनुदान',
    'serviceHooks.pm-fb-enrollment.question': 'पीक विम्यात मदत हवी आहे?',
    'serviceHooks.pm-fb-enrollment.b0': 'मोफत नोंदणी सहाय्य',
    'serviceHooks.pm-fb-enrollment.b1': 'दावा दाखल करण्यासाठी सहाय्य',
    'serviceHooks.cooperative-training.question': 'सहकारी कौशल्य विकसित करू इच्छिता?',
    'serviceHooks.cooperative-training.b0': 'व्यवस्थापन अभ्यासक्रम',
    'serviceHooks.cooperative-training.b1': 'कायदेशीर अनुपालन प्रशिक्षण',
    'serviceHooks.digital-banking.question': 'डिजिटल बँकिंग प्रवेश हवा आहे?',
    'serviceHooks.digital-banking.b0': 'UPI आणि नेट बँकिंग',
    'serviceHooks.digital-banking.b1': 'मोबाइल बँकिंग ॲप्स',
  },
  bn: {
    'serviceHooks.pacs-membership.question': 'ঋণ এবং সেবায় প্রবেশ চান?',
    'serviceHooks.pacs-membership.b0': 'সাশ্রয়ী ঋণ',
    'serviceHooks.pacs-membership.b1': 'স্টোরেজ ও ইনপুট',
    'serviceHooks.pacs-membership.b2': 'অভিযোগ সহায়তা',
    'serviceHooks.short-term-crop-credit.question': 'আপনার ফসলের জন্য ঋণ দরকার?',
    'serviceHooks.short-term-crop-credit.b0': 'মৌসুমি চাষার চাহিদা পূরণ করে',
    'serviceHooks.short-term-crop-credit.b1': 'সাবসিডি সুদের হার',
    'serviceHooks.godown-storage.question': 'নিরাপদ স্টোরেজ খুঁজছেন?',
    'serviceHooks.godown-storage.b0': 'জোরপূর্বক বিক্রি এড়িয়ে চলুন',
    'serviceHooks.godown-storage.b1': 'স্টকের বিপরীতে বন্ধক ঋণ',
    'serviceHooks.agro-input-supply.question': 'ভালো বীজ ও সার দরকার?',
    'serviceHooks.agro-input-supply.b0': 'প্রমাণিত ইনপুট',
    'serviceHooks.agro-input-supply.b1': 'যথার্থ সমবায় মূল্য',
    'serviceHooks.pmfby-enrolment.question': 'ফসল বীমা কভারেজ চান?',
    'serviceHooks.pmfby-enrolment.b0': 'প্রাকৃতিক দুর্যোগ সুরক্ষা',
    'serviceHooks.pmfby-enrolment.b1': 'কম প্রিমিয়াম হার',
    'serviceHooks.cooperative-subsidy.question': 'সমবায় অবকাঠামোর জন্য তহবিল দরকার?',
    'serviceHooks.cooperative-subsidy.b0': 'পুঁজি সাবসিডি',
    'serviceHooks.cooperative-subsidy.b1': 'সুদ সাবসিডি',
    'serviceHooks.pm-fb-enrollment.question': 'ফসল বীমায় সাহায্য দরকার?',
    'serviceHooks.pm-fb-enrollment.b0': 'বিনামূল্যে ভর্তি সহায়তা',
    'serviceHooks.pm-fb-enrollment.b1': 'দাবি দায়েরে সহায়তা',
    'serviceHooks.cooperative-training.question': 'সমবায় দক্ষতা তৈরি করতে চান?',
    'serviceHooks.cooperative-training.b0': 'ব্যবস্থাপনা কোর্স',
    'serviceHooks.cooperative-training.b1': 'আইনি সম্মতি প্রশিক্ষণ',
    'serviceHooks.digital-banking.question': 'ডিজিটাল ব্যাংকিং অ্যাক্সেস দরকার?',
    'serviceHooks.digital-banking.b0': 'UPI ও নেট ব্যাংকিং',
    'serviceHooks.digital-banking.b1': 'মোবাইল ব্যাংকিং অ্যাপ',
  },
  ta: {
    'serviceHooks.pacs-membership.question': 'கடன் மற்றும் சேவைகளை அணுக விரும்புகிறீர்களா?',
    'serviceHooks.pacs-membership.b0': 'மலிவான கடன்',
    'serviceHooks.pacs-membership.b1': 'சேமிப்பு மற்றும் உள்ளீடுகள்',
    'serviceHooks.pacs-membership.b2': 'புகார் உதவி',
    'serviceHooks.short-term-crop-credit.question': 'உங்கள் பயிருக்கு கடன் தேவையா?',
    'serviceHooks.short-term-crop-credit.b0': 'பருவகால விவசாயத் தேவைகளை பூர்த்தி செய்கிறது',
    'serviceHooks.short-term-crop-credit.b1': 'மானிய வட்டி விகிதம்',
    'serviceHooks.godown-storage.question': 'பாதுகாப்பான சேமிப்பு தேடுகிறீர்களா?',
    'serviceHooks.godown-storage.b0': 'கட்டாய விற்பனையைத் தவிர்க்கவும்',
    'serviceHooks.godown-storage.b1': 'சரக்குகளுக்கு எதிராக அடமான கடன்',
    'serviceHooks.agro-input-supply.question': 'நல்ல விதைகள் மற்றும் உரம் தேவையா?',
    'serviceHooks.agro-input-supply.b0': 'சான்றிதழ் பெற்ற உள்ளீடுகள்',
    'serviceHooks.agro-input-supply.b1': 'நியாயமான கூட்டுறவு விலை',
    'serviceHooks.pmfby-enrolment.question': 'பயிர் காப்பீடு கவரேஜ் வேண்டுமா?',
    'serviceHooks.pmfby-enrolment.b0': 'இயற்கை பேரிடர் பாதுகாப்பு',
    'serviceHooks.pmfby-enrolment.b1': 'குறைந்த பிரீமியம் விகிதம்',
    'serviceHooks.cooperative-subsidy.question': 'கூட்டுறவு உள்கட்டமைப்புக்கு நிதி தேவையா?',
    'serviceHooks.cooperative-subsidy.b0': 'மூலதன மானியம்',
    'serviceHooks.cooperative-subsidy.b1': 'வட்டி மானியம்',
    'serviceHooks.pm-fb-enrollment.question': 'பயிர் காப்பீட்டில் உதவி தேவையா?',
    'serviceHooks.pm-fb-enrollment.b0': 'இலவச சேர்க்கை உதவி',
    'serviceHooks.pm-fb-enrollment.b1': 'க்ளெய்ம் தாக்கல் உதவி',
    'serviceHooks.cooperative-training.question': 'கூட்டுறவு திறன்களை உருவாக்க விரும்புகிறீர்களா?',
    'serviceHooks.cooperative-training.b0': 'மேலாண்மை படிப்புகள்',
    'serviceHooks.cooperative-training.b1': 'சட்ட இணக்க பயிற்சி',
    'serviceHooks.digital-banking.question': 'டிஜிட்டல் வங்கி அணுகல் தேவையா?',
    'serviceHooks.digital-banking.b0': 'UPI மற்றும் நெட் வங்கி',
    'serviceHooks.digital-banking.b1': 'மொபைல் வங்கி ஆப்கள்',
  },
  te: {
    'serviceHooks.pacs-membership.question': 'రుణం మరియు సేవలకు యాక్సెస్ కావాలా?',
    'serviceHooks.pacs-membership.b0': 'సరసమైన రుణం',
    'serviceHooks.pacs-membership.b1': 'నిల్వ మరియు ఇన్\u200Cపుట్\u200Cలు',
    'serviceHooks.pacs-membership.b2': 'ఫిర్యాదు సహాయం',
    'serviceHooks.short-term-crop-credit.question': 'మీ పంటకు రుణం కావాలా?',
    'serviceHooks.short-term-crop-credit.b0': 'సీజనల్ వ్యవసాయ అవసరాలను తీరుస్తుంది',
    'serviceHooks.short-term-crop-credit.b1': 'సబ్సిడీ వడ్డీ రేటు',
    'serviceHooks.godown-storage.question': 'సురక్షిత నిల్వ కోసం చూస్తున్నారా?',
    'serviceHooks.godown-storage.b0': 'బలవంతపు అమ్మకాలను నివారించండి',
    'serviceHooks.godown-storage.b1': 'స్టాక్\u200Cకు వ్యతిరేకంగా తాకట్టు రుణం',
    'serviceHooks.agro-input-supply.question': 'మంచి విత్తనాలు మరియు ఎరువులు కావాలా?',
    'serviceHooks.agro-input-supply.b0': 'ధృవీకరించబడిన ఇన్\u200Cపుట్\u200Cలు',
    'serviceHooks.agro-input-supply.b1': 'న్యాయమైన సహకార ధర',
    'serviceHooks.pmfby-enrolment.question': 'పంట బీమా కవరేజ్ కావాలా?',
    'serviceHooks.pmfby-enrolment.b0': 'ప్రకృతి వైపరీత్యం రక్షణ',
    'serviceHooks.pmfby-enrolment.b1': 'తక్కువ ప్రీమియం రేటు',
    'serviceHooks.cooperative-subsidy.question': 'సహకార మౌలిక సదుపాయాల కోసం నిధులు కావాలా?',
    'serviceHooks.cooperative-subsidy.b0': 'మూలధన సబ్సిడీ',
    'serviceHooks.cooperative-subsidy.b1': 'వడ్డీ సబ్సిడీ',
    'serviceHooks.pm-fb-enrollment.question': 'పంట బీమాలో సహాయం కావాలా?',
    'serviceHooks.pm-fb-enrollment.b0': 'ఉచిత నమోదు సహాయం',
    'serviceHooks.pm-fb-enrollment.b1': 'క్లెయిమ్ దాఖలు సహాయం',
    'serviceHooks.cooperative-training.question': 'సహకార నైపుణ్యాలు నిర్మించాలనుకుంటున్నారా?',
    'serviceHooks.cooperative-training.b0': 'నిర్వహణ కోర్సులు',
    'serviceHooks.cooperative-training.b1': 'చట్టపరమైన అనుసరణ శిక్షణ',
    'serviceHooks.digital-banking.question': 'డిజిటల్ బ్యాంకింగ్ యాక్సెస్ కావాలా?',
    'serviceHooks.digital-banking.b0': 'UPI & నెట్ బ్యాంకింగ్',
    'serviceHooks.digital-banking.b1': 'మొబైల్ బ్యాంకింగ్ యాప్\u200Cలు',
  },
  kn: {
    'serviceHooks.pacs-membership.question': 'ಸಾಲ ಮತ್ತು ಸೇವೆಗಳಿಗೆ ಪ್ರವೇಶ ಬೇಕೇ?',
    'serviceHooks.pacs-membership.b0': 'ಕೈಗೆಟುಕುವ ಸಾಲ',
    'serviceHooks.pacs-membership.b1': 'ಸಂಗ್ರಹಣೆ ಮತ್ತು ಇನ್\u200Cಪುಟ್\u200Cಗಳು',
    'serviceHooks.pacs-membership.b2': 'ದೂರು ಸಹಾಯ',
    'serviceHooks.short-term-crop-credit.question': 'ನಿಮ್ಮ ಬೆಳೆಗೆ ಸಾಲ ಬೇಕೇ?',
    'serviceHooks.short-term-crop-credit.b0': 'ಋತುಮಾನದ ಕೃಷಿ ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸುತ್ತದೆ',
    'serviceHooks.short-term-crop-credit.b1': 'ಸಬ್ಸಿಡಿ ಬಡ್ಡಿ ದರ',
    'serviceHooks.godown-storage.question': 'ಸುರಕ್ಷಿತ ಸಂಗ್ರಹಣೆ ಹುಡುಕುತ್ತಿದ್ದೀರಾ?',
    'serviceHooks.godown-storage.b0': 'ಒತ್ತಡ ಮಾರಾಟವನ್ನು ತಪ್ಪಿಸಿ',
    'serviceHooks.godown-storage.b1': 'ಸ್ಟಾಕ್\u200Cನ ವಿರುದ್ಧ ಜಮೀನುದಾರಿ ಸಾಲ',
    'serviceHooks.agro-input-supply.question': 'ಒಳ್ಳೆಯ ಬೀಜ ಮತ್ತು ಗೊಬ್ಬರ ಬೇಕೇ?',
    'serviceHooks.agro-input-supply.b0': 'ಪ್ರಮಾಣೀಕೃತ ಇನ್\u200Cಪುಟ್\u200Cಗಳು',
    'serviceHooks.agro-input-supply.b1': 'ನ್ಯಾಯಯುತ ಸಹಕಾರ ಬೆಲೆ',
    'serviceHooks.pmfby-enrolment.question': 'ಬೆಳೆ ವಿಮೆ ಕವರೇಜ್ ಬೇಕೇ?',
    'serviceHooks.pmfby-enrolment.b0': 'ಪ್ರಾಕೃತಿಕ ವಿಪತ್ತು ರಕ್ಷಣೆ',
    'serviceHooks.pmfby-enrolment.b1': 'ಕಡಿಮೆ ಪ್ರೀಮಿಯಂ ದರ',
    'serviceHooks.cooperative-subsidy.question': 'ಸಹಕಾರ ಮೂಲಸೌಕರ್ಯಕ್ಕೆ ಹಣಕಾಸು ಬೇಕೇ?',
    'serviceHooks.cooperative-subsidy.b0': 'ಬಂಡವಾಳ ಸಬ್ಸಿಡಿ',
    'serviceHooks.cooperative-subsidy.b1': 'ಬಡ್ಡಿ ಸಬ್ಸಿಡಿ',
    'serviceHooks.pm-fb-enrollment.question': 'ಬೆಳೆ ವಿಮೆಯಲ್ಲಿ ಸಹಾಯ ಬೇಕೇ?',
    'serviceHooks.pm-fb-enrollment.b0': 'ಉಚಿತ ನೋಂದಣಿ ಸಹಾಯ',
    'serviceHooks.pm-fb-enrollment.b1': 'ಕ್ಲೇಮ್ ದಾಖಲಿಸುವ ಸಹಾಯ',
    'serviceHooks.cooperative-training.question': 'ಸಹಕಾರ ಕೌಶಲ್ಯಗಳನ್ನು ನಿರ್ಮಿಸಲು ಬಯಸುವಿರಾ?',
    'serviceHooks.cooperative-training.b0': 'ನಿರ್ವಹಣಾ ಕೋರ್ಸ್\u200Cಗಳು',
    'serviceHooks.cooperative-training.b1': 'ಕಾನೂನು ಅನುಸರಣ ತರಬೇತಿ',
    'serviceHooks.digital-banking.question': 'ಡಿಜಿಟಲ್ ಬ್ಯಾಂಕಿಂಗ್ ಪ್ರವೇಶ ಬೇಕೇ?',
    'serviceHooks.digital-banking.b0': 'UPI & ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್',
    'serviceHooks.digital-banking.b1': 'ಮೊಬೈಲ್ ಬ್ಯಾಂಕಿಂಗ್ ಆ್ಯಪ್\u200Cಗಳು',
  },
  pa: {
    'serviceHooks.pacs-membership.question': 'ਕਰਜ਼ੇ ਅਤੇ ਸੇਵਾਵਾਂ ਤੱਕ ਪਹੁੰਚ ਚਾਹੁੰਦੇ ਹੋ?',
    'serviceHooks.pacs-membership.b0': 'ਕਿਫ਼ਾਇਤੀ ਕਰਜ਼ਾ',
    'serviceHooks.pacs-membership.b1': 'ਸਟੋਰੇਜ ਅਤੇ ਇਨਪੁੱਟ',
    'serviceHooks.pacs-membership.b2': 'ਸ਼ਿਕਾਇਤ ਸਹਾਇਤਾ',
    'serviceHooks.short-term-crop-credit.question': 'ਆਪਣੀ ਫਸਲ ਲਈ ਕਰਜ਼ਾ ਚਾਹੀਦਾ ਹੈ?',
    'serviceHooks.short-term-crop-credit.b0': 'ਮੌਸਮੀ ਖੇਤੀ ਦੀਆਂ ਲੋੜਾਂ ਪੂਰੀਆਂ ਕਰਦਾ ਹੈ',
    'serviceHooks.short-term-crop-credit.b1': 'ਸਬਸਿਡੀ ਵਾਲਾ ਵਿਆਜ ਦਰ',
    'serviceHooks.godown-storage.question': 'ਸੁਰੱਖਿਅਤ ਸਟੋਰੇਜ ਲੱਭ ਰਹੇ ਹੋ?',
    'serviceHooks.godown-storage.b0': 'ਜ਼ਬਰਦਸਤੀ ਵਿਕਰੀਆਂ ਤੋਂ ਬਚੋ',
    'serviceHooks.godown-storage.b1': 'ਸਟਾਕ ਦੇ ਬਦਲੇ ਗਿਰਵੀ ਕਰਜ਼ਾ',
    'serviceHooks.agro-input-supply.question': 'ਚੰਗੇ ਬੀਜ ਅਤੇ ਖਾਦ ਚਾਹੀਦੀ ਹੈ?',
    'serviceHooks.agro-input-supply.b0': 'ਪ੍ਰਮਾਣਿਤ ਇਨਪੁੱਟ',
    'serviceHooks.agro-input-supply.b1': 'ਯੋਗ ਸਹਿਕਾਰੀ ਕੀਮਤ',
    'serviceHooks.pmfby-enrolment.question': 'ਫਸਲ ਬੀਮੇ ਦਾ ਕਵਰੇਜ ਚਾਹੀਦਾ ਹੈ?',
    'serviceHooks.pmfby-enrolment.b0': 'ਕੁਦਰਤੀ ਆਫ਼ਤ ਸੁਰੱਖਿਆ',
    'serviceHooks.pmfby-enrolment.b1': 'ਘੱਟ ਪ੍ਰੀਮੀਅਮ ਦਰ',
    'serviceHooks.cooperative-subsidy.question': 'ਸਹਿਕਾਰੀ ਢਾਂਚੇ ਲਈ ਫੰਡਿੰਗ ਚਾਹੀਦੀ ਹੈ?',
    'serviceHooks.cooperative-subsidy.b0': 'ਪੂੰਜੀ ਸਬਸਿਡੀ',
    'serviceHooks.cooperative-subsidy.b1': 'ਵਿਆਜ ਸਬਸਿਡੀ',
    'serviceHooks.pm-fb-enrollment.question': 'ਫਸਲ ਬੀਮੇ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    'serviceHooks.pm-fb-enrollment.b0': 'ਮੁਫ਼ਤ ਦਾਖਲਾ ਸਹਾਇਤਾ',
    'serviceHooks.pm-fb-enrollment.b1': 'ਦਾਅਵਾ ਦਾਇਰ ਕਰਨ ਵਿੱਚ ਸਹਾਇਤਾ',
    'serviceHooks.cooperative-training.question': 'ਸਹਿਕਾਰੀ ਹੁਨਰ ਬਣਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
    'serviceHooks.cooperative-training.b0': 'ਪ੍ਰਬੰਧਨ ਕੋਰਸ',
    'serviceHooks.cooperative-training.b1': 'ਕਾਨੂੰਨੀ ਅਨੁਸਰਣ ਸਿਖਲਾਈ',
    'serviceHooks.digital-banking.question': 'ਡਿਜੀਟਲ ਬੈਂਕਿੰਗ ਪਹੁੰਚ ਚਾਹੀਦੀ ਹੈ?',
    'serviceHooks.digital-banking.b0': 'UPI ਅਤੇ ਨੈੱਟ ਬੈਂਕਿੰਗ',
    'serviceHooks.digital-banking.b1': 'ਮੋਬਾਈਲ ਬੈਂਕਿੰਗ ਐਪਾਂ',
  },
  gu: {
    'serviceHooks.pacs-membership.question': 'ધિરાણ અને સેવાઓની પહોંચ જોઈએ છે?',
    'serviceHooks.pacs-membership.b0': 'સસ્તું ધિરાણ',
    'serviceHooks.pacs-membership.b1': 'સંગ્રહ અને ઇનપુટ',
    'serviceHooks.pacs-membership.b2': 'ફરિયાદ સહાય',
    'serviceHooks.short-term-crop-credit.question': 'તમારા પાક માટે ધિરાણ જોઈએ છે?',
    'serviceHooks.short-term-crop-credit.b0': 'મોસમી ખેતીની જરૂરિયાતો પૂરી કરે છે',
    'serviceHooks.short-term-crop-credit.b1': 'સબસિડી વ્યાજ દર',
    'serviceHooks.godown-storage.question': 'સુરક્ષિત સંગ્રહ શોધી રહ્યા છો?',
    'serviceHooks.godown-storage.b0': 'જબરજસ્ત વેચાણ ટાળો',
    'serviceHooks.godown-storage.b1': 'સ્ટોક સામે ગીરવે ધિરાણ',
    'serviceHooks.agro-input-supply.question': 'સારા બીજ અને ખાતર જોઈએ છે?',
    'serviceHooks.agro-input-supply.b0': 'પ્રમાણિત ઇનપુટ',
    'serviceHooks.agro-input-supply.b1': 'યોગ્ય સહકારી કિંમત',
    'serviceHooks.pmfby-enrolment.question': 'પાક વીમા કવરેજ જોઈએ છે?',
    'serviceHooks.pmfby-enrolment.b0': 'કુદરતી આપત્તિ રક્ષણ',
    'serviceHooks.pmfby-enrolment.b1': 'ઓછા પ્રીમિયમ દર',
    'serviceHooks.cooperative-subsidy.question': 'સહકારી ઈન્ફ્રા માટે ફંડિંગ જોઈએ છે?',
    'serviceHooks.cooperative-subsidy.b0': 'મૂડી સબસિડી',
    'serviceHooks.cooperative-subsidy.b1': 'વ્યાજ સબસિડી',
    'serviceHooks.pm-fb-enrollment.question': 'પાક વીમામાં મદદ જોઈએ છે?',
    'serviceHooks.pm-fb-enrollment.b0': 'મફત નોંધણી સહાય',
    'serviceHooks.pm-fb-enrollment.b1': 'દાવો દાખલ કરવામાં સહાય',
    'serviceHooks.cooperative-training.question': 'સહકારી કૌશલ્ય બનાવવા માંગો છો?',
    'serviceHooks.cooperative-training.b0': 'વ્યવસ્થાપન કોર્સ',
    'serviceHooks.cooperative-training.b1': 'કાનૂની અનુપાલન તાલીમ',
    'serviceHooks.digital-banking.question': 'ડિજિટલ બેંકિંગ ઍક્સેસ જોઈએ છે?',
    'serviceHooks.digital-banking.b0': 'UPI અને નેટ બેંકિંગ',
    'serviceHooks.digital-banking.b1': 'મોબાઇલ બેંકિંગ એપ્સ',
  },
  or: {
    'serviceHooks.pacs-membership.question': 'ଋଣ ଏବଂ ସେବା ପ୍ରାପ୍ତି କରିବାକୁ ଚାହୁଁଛନ୍ତି?',
    'serviceHooks.pacs-membership.b0': 'ସାଶ୍ରୟୀ ଋଣ',
    'serviceHooks.pacs-membership.b1': 'ଭଣ୍ଡାର ଏବଂ ଇନପୁଟ୍',
    'serviceHooks.pacs-membership.b2': 'ଅଭିଯୋଗ ସହାୟତା',
    'serviceHooks.short-term-crop-credit.question': 'ଆପଣଙ୍କ ଫସଲ ପାଇଁ ଋଣ ଦରକାର?',
    'serviceHooks.short-term-crop-credit.b0': 'ଋତୁକାଳୀନ ଚାଷ ଆବଶ୍ୟକତା ପୂରଣ କରେ',
    'serviceHooks.short-term-crop-credit.b1': 'ସବସିଡି ସୁଧ ହାର',
    'serviceHooks.godown-storage.question': 'ସୁରକ୍ଷିତ ଭଣ୍ଡାର ଖୋଜୁଛନ୍ତି କି?',
    'serviceHooks.godown-storage.b0': 'ବାଧ୍ୟତାମୂଳକ ବିକ୍ରୟ ଏଡ଼ାନ୍ତୁ',
    'serviceHooks.godown-storage.b1': 'ଷ୍ଟକ୍ ବିରୁଦ୍ଧରେ ବନ୍ଧକ ଋଣ',
    'serviceHooks.agro-input-supply.question': 'ଭଲ ବିହନ ଏବଂ ସାର ଦରକାର?',
    'serviceHooks.agro-input-supply.b0': 'ପ୍ରମାଣିତ ଇନପୁଟ୍',
    'serviceHooks.agro-input-supply.b1': 'ଯଥାର୍ଥ ସହକାରୀ ମୂଲ୍ୟ',
    'serviceHooks.pmfby-enrolment.question': 'ଫସଲ ବୀମା କଭରେଜ ଦରକାର?',
    'serviceHooks.pmfby-enrolment.b0': 'ପ୍ରାକୃତିକ ବିପର୍ଯ୍ୟୟ ସୁରକ୍ଷା',
    'serviceHooks.pmfby-enrolment.b1': 'କମ୍ ପ୍ରିମିୟମ୍ ହାର',
    'serviceHooks.cooperative-subsidy.question': 'ସହକାରୀ ଭିତ୍ତିଭୂମି ପାଇଁ ଅର୍ଥ ଦରକାର?',
    'serviceHooks.cooperative-subsidy.b0': 'ମୂଳଧନ ସବସିଡି',
    'serviceHooks.cooperative-subsidy.b1': 'ସୁଧ ସବସିଡି',
    'serviceHooks.pm-fb-enrollment.question': 'ଫସଲ ବୀମାରେ ସାହାଯ୍ୟ ଦରକାର?',
    'serviceHooks.pm-fb-enrollment.b0': 'ମାଗଣା ନାମାଙ୍କନ ସହାୟତା',
    'serviceHooks.pm-fb-enrollment.b1': 'ଦାବି ଦାଖଲ ସହାୟତା',
    'serviceHooks.cooperative-training.question': 'ସହକାରୀ ଦକ୍ଷତା ନିର୍ମାଣ କରିବାକୁ ଚାହୁଁଛନ୍ତି?',
    'serviceHooks.cooperative-training.b0': 'ପରିଚାଳନା କୋର୍ସ',
    'serviceHooks.cooperative-training.b1': 'ଆଇନଗତ ସମ୍ମତି ତାଲିମ',
    'serviceHooks.digital-banking.question': 'ଡିଜିଟାଲ୍ ବ୍ୟାଙ୍କିଂ ପ୍ରବେଶ ଦରକାର?',
    'serviceHooks.digital-banking.b0': 'UPI ଏବଂ ନେଟ୍ ବ୍ୟାଙ୍କିଂ',
    'serviceHooks.digital-banking.b1': 'ମୋବାଇଲ୍ ବ୍ୟାଙ୍କିଂ ଆପ୍',
  },
  ml: {
    'serviceHooks.pacs-membership.question': 'വായ്പയും സേവനങ്ങളും ആക്സസ് ചെയ്യാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?',
    'serviceHooks.pacs-membership.b0': 'താങ്ങാവുന്ന വായ്പ',
    'serviceHooks.pacs-membership.b1': 'സംഭരണം & ഇൻപുട്ടുകൾ',
    'serviceHooks.pacs-membership.b2': 'പരാതി സഹായം',
    'serviceHooks.short-term-crop-credit.question': 'നിങ്ങളുടെ വിളയ്ക്ക് വായ്പ വേണോ?',
    'serviceHooks.short-term-crop-credit.b0': 'ഋതുവിനനുസൃതമായ കൃഷി ആവശ്യങ്ങൾ നിറവേറ്റുന്നു',
    'serviceHooks.short-term-crop-credit.b1': 'സബ്സിഡി പലിശ നിരക്ക്',
    'serviceHooks.godown-storage.question': 'സുരക്ഷിത സംഭരണം തിരയുകയാണോ?',
    'serviceHooks.godown-storage.b0': 'നിർബന്ധിത വിൽപ്പന ഒഴിവാക്കുക',
    'serviceHooks.godown-storage.b1': 'സ്റ്റോക്കിനെതിരെ പണയ വായ്പ',
    'serviceHooks.agro-input-supply.question': 'നല്ല വിത്തുകളും വളവും വേണോ?',
    'serviceHooks.agro-input-supply.b0': 'സർട്ടിഫൈഡ് ഇൻപുട്ടുകൾ',
    'serviceHooks.agro-input-supply.b1': 'ന്യായമായ സഹകരണ വില',
    'serviceHooks.pmfby-enrolment.question': 'വിള ഇൻഷുറൻസ് കവറേജ് വേണോ?',
    'serviceHooks.pmfby-enrolment.b0': 'പ്രകൃതിദുരന്ത സംരക്ഷണം',
    'serviceHooks.pmfby-enrolment.b1': 'കുറഞ്ഞ പ്രീമിയം നിരക്ക്',
    'serviceHooks.cooperative-subsidy.question': 'സഹകരണ അടിസ്ഥാന സൗകര്യത്തിന് ധനസഹായം വേണോ?',
    'serviceHooks.cooperative-subsidy.b0': 'മൂലധന സബ്സിഡി',
    'serviceHooks.cooperative-subsidy.b1': 'പലിശ സബ്സിഡി',
    'serviceHooks.pm-fb-enrollment.question': 'വിള ഇൻഷുറൻസിൽ സഹായം വേണോ?',
    'serviceHooks.pm-fb-enrollment.b0': 'സൗജന്യ ചേരൽ സഹായം',
    'serviceHooks.pm-fb-enrollment.b1': 'ക്ലെയിം ഫയലിംഗ് സഹായം',
    'serviceHooks.cooperative-training.question': 'സഹകരണ നൈപുണ്യം കെട്ടിപ്പടുക്കാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?',
    'serviceHooks.cooperative-training.b0': 'മാനേജ്മെന്റ് കോഴ്സുകൾ',
    'serviceHooks.cooperative-training.b1': 'നിയമ അനുസരണ പരിശീലനം',
    'serviceHooks.digital-banking.question': 'ഡിജിറ്റൽ ബാങ്കിംഗ് ആക്സസ് വേണോ?',
    'serviceHooks.digital-banking.b0': 'UPI & നെറ്റ് ബാങ്കിംഗ്',
    'serviceHooks.digital-banking.b1': 'മൊബൈൽ ബാങ്കിംഗ് ആപ്പുകൾ',
  },
  ur: {
    'serviceHooks.pacs-membership.question': 'قرض اور خدمات تک رسائی چاہتے ہیں؟',
    'serviceHooks.pacs-membership.b0': 'سستا قرض',
    'serviceHooks.pacs-membership.b1': 'ذخیرہ اور انپٹس',
    'serviceHooks.pacs-membership.b2': 'شکایت معاونت',
    'serviceHooks.short-term-crop-credit.question': 'اپنی فصل کے لیے قرض چاہیے؟',
    'serviceHooks.short-term-crop-credit.b0': 'موسمی کھیتی کی ضروریات پوری کرتا ہے',
    'serviceHooks.short-term-crop-credit.b1': 'سبسڈی شدہ سود کی شرح',
    'serviceHooks.godown-storage.question': 'محفوظ ذخیرہ تلاش کر رہے ہیں؟',
    'serviceHooks.godown-storage.b0': 'مجبوری فروخت سے بچیں',
    'serviceHooks.godown-storage.b1': 'اسٹاک کے بدلے گروی قرض',
    'serviceHooks.agro-input-supply.question': 'اچھے بیج اور کھاد چاہیے؟',
    'serviceHooks.agro-input-supply.b0': 'تصدیق شدہ انپٹس',
    'serviceHooks.agro-input-supply.b1': 'مناسب کوآپریٹو قیمت',
    'serviceHooks.pmfby-enrolment.question': 'فصل بیمے کا کوریج چاہیے؟',
    'serviceHooks.pmfby-enrolment.b0': 'قدرتی آفت کا تحفظ',
    'serviceHooks.pmfby-enrolment.b1': 'کم پریمیم شرح',
    'serviceHooks.cooperative-subsidy.question': 'کوآپریٹو انفراسٹرکچر کے لیے فنڈنگ چاہیے؟',
    'serviceHooks.cooperative-subsidy.b0': 'سرمایہ سبسڈی',
    'serviceHooks.cooperative-subsidy.b1': 'سود سبسڈی',
    'serviceHooks.pm-fb-enrollment.question': 'فصل بیمے میں مدد چاہیے؟',
    'serviceHooks.pm-fb-enrollment.b0': 'مفت اندراج معاونت',
    'serviceHooks.pm-fb-enrollment.b1': 'دعویٰ درج کرنے میں معاونت',
    'serviceHooks.cooperative-training.question': 'کوآپریٹو مہارتیں بنانا چاہتے ہیں؟',
    'serviceHooks.cooperative-training.b0': 'مینجمنٹ کورسز',
    'serviceHooks.cooperative-training.b1': 'قانونی تعمّل تربیت',
    'serviceHooks.digital-banking.question': 'ڈیجیٹل بینکنگ رسائی چاہیے؟',
    'serviceHooks.digital-banking.b0': 'UPI اور نیٹ بینکنگ',
    'serviceHooks.digital-banking.b1': 'موبائل بینکنگ ایپس',
  },
};

// Each language section starts with a unique "schemes.learnHow" line.
// We find that line, then find the NEXT "services.detail.startConversation" after it,
// and insert before the NEXT language's section (identified by next "schemes.learnHow").
const langOrder = ['hi', 'mr', 'bn', 'ta', 'te', 'kn', 'pa', 'gu', 'or', 'ml', 'ur'];
const langLearnHow = {
  hi: '"schemes.learnHow": "जानें यह कैसे मदद करता है"',
  mr: '"schemes.learnHow": "जाणा हे कशी मदत करते"',
  bn: '"schemes.learnHow": "জানুন এটি কীভাবে সাহায্য করে"',
  ta: '"schemes.learnHow": "இது எவ்வாறு உதவுகிறது என்று அறிக"',
  te: '"schemes.learnHow": "ఇది ఎలా సహాయపడుతుందో తెలుసుకోండి"',
  kn: '"schemes.learnHow": "ಇದು ಹೇಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ ಎಂದು ತಿಳಿಯಿರಿ"',
  pa: '"schemes.learnHow": "ਜਾਣੋ ਇਹ ਕਿਵੇਂ ਮਦਦ ਕਰਦਾ ਹੈ"',
  gu: '"schemes.learnHow": "જાણો આ કેવી રીતે મદદ કરે છે"',
  or: '"schemes.learnHow": "ଜାଣନ୍ତୁ ଏହା କିପରି ସାହାଯ୍ୟ କରେ"',
  ml: '"schemes.learnHow": "ഇത് എങ്ങനെ സഹായിക്കുന്നു എന്ന് അറിയുക"',
  ur: '"schemes.learnHow": "جانیں یہ کیسے مدد کرتا ہے"',
};

// Process in reverse order to avoid index shifting
for (let i = langOrder.length - 1; i >= 0; i--) {
  const lang = langOrder[i];
  const hooks = langHooks[lang];
  const learnHowKey = langLearnHow[lang];

  const langStart = content.indexOf(learnHowKey);
  if (langStart === -1) {
    console.log(`WARN: Could not find section for ${lang}`);
    continue;
  }

  // Find services.detail.startConversation within this section
  // Search between langStart and the next language section (or end of file)
  const nextLangIdx = i < langOrder.length - 1
    ? content.indexOf(langLearnHow[langOrder[i + 1]], langStart + 1)
    : content.length;

  const convKey = '"services.detail.startConversation"';
  const convIdx = content.indexOf(convKey, langStart);
  if (convIdx === -1 || convIdx > nextLangIdx) {
    console.log(`WARN: Could not find services.detail.startConversation for ${lang}`);
    continue;
  }

  const lineEnd = content.indexOf('\n', convIdx);
  if (lineEnd === -1) continue;

  const lines = Object.entries(hooks).map(([k, v]) => `  "${k}": "${v}",`).join('\n');
  const insertion = '\n' + lines + '\n';

  content = content.slice(0, lineEnd + 1) + insertion + content.slice(lineEnd + 1);
}

fs.writeFileSync(file, content);
console.log('Done - added serviceHooks for all languages');
